In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## Create the Targets

In [5]:
data['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets=np.where(data['Absenteeism Time in Hours']>3,1,0)                #checks if a condition has been satisfied and assign a value accordingly

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data['Excessive Absenteeism']=targets

In [9]:
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
new_data=data.drop(['Absenteeism Time in Hours'],axis=1)

In [12]:
new_data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

## Select inputs for regression

In [13]:
new_data.shape

(700, 15)

In [14]:
new_data.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [15]:
unscaled_inputs=new_data.iloc[:,:-1]

## Standardize the data

In [16]:
from sklearn.preprocessing import StandardScaler
absenteeism_scalar=StandardScaler()   #absenteeism_scaler will be used to subtract mean and divide standard deviation variablewise

In [17]:
absenteeism_scalar.fit(unscaled_inputs)

StandardScaler()

In [19]:
scaled_inputs=absenteeism_scalar.transform(unscaled_inputs)

In [20]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [21]:
scaled_inputs.shape

(700, 14)

## Split the data into train and test and Shuffle

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  2.8430157 ],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          0.88046927,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [27]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [28]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [29]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


## Logistic regression with sklearn

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [31]:
reg=LogisticRegression()

In [32]:
reg.fit(x_train,y_train)        #fit(): fits the model acc to given training data

LogisticRegression()

In [33]:
reg.score(x_train,y_train)  #score(): it returns the accuracy on the given testdata and labels

0.7803571428571429

### manually checking the accuracy

In [34]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [36]:
model_outputs==y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [37]:
np.sum(model_outputs==y_train)

437

In [38]:
model_outputs.shape[0]

560

In [39]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7803571428571429

### Finding intercepts and coefficients

In [40]:
reg.intercept_

array([-0.21150898])

In [41]:
reg.coef_

array([[ 2.07192269,  0.33075027,  1.56390046,  1.31283678,  0.02577323,
        -0.08622837,  0.72326969, -0.06149037, -0.20628304, -0.02865604,
         0.3259002 , -0.16141702,  0.38153429, -0.32129837]])

In [42]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [43]:
feature_name=unscaled_inputs.columns.values

In [45]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  coefficient
0                  Reason_1     2.071923
1                  Reason_2     0.330750
2                  Reason_3     1.563900
3                  Reason_4     1.312837
4               Month Value     0.025773
5           Day of the Week    -0.086228
6    Transportation Expense     0.723270
7          Distance to Work    -0.061490
8                       Age    -0.206283
9   Daily Work Load Average    -0.028656
10          Body Mass Index     0.325900
11                Education    -0.161417
12                 Children     0.381534
13                      Pet    -0.321298

In [46]:
summary_table.index=summary_table.index+1 #we shift all indices by one so as to make place for intercept at the top of summary table
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  coefficient
0                 Intercept    -0.211509
1                  Reason_1     2.071923
2                  Reason_2     0.330750
3                  Reason_3     1.563900
4                  Reason_4     1.312837
5               Month Value     0.025773
6           Day of the Week    -0.086228
7    Transportation Expense     0.723270
8          Distance to Work    -0.061490
9                       Age    -0.206283
10  Daily Work Load Average    -0.028656
11          Body Mass Index     0.325900
12                Education    -0.161417
13                 Children     0.381534
14                      Pet    -0.321298

### Interpreting the coefficients

In [47]:
summary_table['Odds_ratio']=np.exp(summary_table.coefficient)

In [48]:
summary_table

Feature name  coefficient  Odds_ratio
0                 Intercept    -0.211509    0.809362
1                  Reason_1     2.071923    7.940075
2                  Reason_2     0.330750    1.392012
3                  Reason_3     1.563900    4.777419
4                  Reason_4     1.312837    3.716702
5               Month Value     0.025773    1.026108
6           Day of the Week    -0.086228    0.917385
7    Transportation Expense     0.723270    2.061162
8          Distance to Work    -0.061490    0.940362
9                       Age    -0.206283    0.813603
10  Daily Work Load Average    -0.028656    0.971751
11          Body Mass Index     0.325900    1.385277
12                Education    -0.161417    0.850937
13                 Children     0.381534    1.464530
14                      Pet    -0.321298    0.725207

In [51]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  coefficient  Odds_ratio
1                  Reason_1     2.071923    7.940075
3                  Reason_3     1.563900    4.777419
4                  Reason_4     1.312837    3.716702
7    Transportation Expense     0.723270    2.061162
13                 Children     0.381534    1.464530
2                  Reason_2     0.330750    1.392012
11          Body Mass Index     0.325900    1.385277
5               Month Value     0.025773    1.026108
10  Daily Work Load Average    -0.028656    0.971751
8          Distance to Work    -0.061490    0.940362
6           Day of the Week    -0.086228    0.917385
12                Education    -0.161417    0.850937
9                       Age    -0.206283    0.813603
0                 Intercept    -0.211509    0.809362
14                      Pet    -0.321298    0.725207

#### A feature is not really imp if :
#### coef is around 0
#### odds ratio is around 1